name: Tests

on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
      - main

jobs:
  swiftlint:
    name: Swiftlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: norio-nomura/action-swiftlint@3.2.1
        with:
          args: --strict

  editorconfig-check:
    name: Editorconfig check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: editorconfig-checker/action-editorconfig-checker@main

      - run: editorconfig-checker

  tests-succeeded:
    name: Tests Succeeded
    needs:
      - swiftlint
      - editorconfig-check

    runs-on: ubuntu-latest
    steps:
      - name: All clear
        run: exit 0
