name: Update Version
run-name: Tag ${{ github.event.inputs.target }}

on:
  workflow_dispatch:
    inputs:
      target:
        description: The tag or reference to use in the form of x.y.z
        required: true

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Git config
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Tag new targets
        run: git tag ${{ github.event.inputs.target }}
      - name: Push new tags
        run: git push origin ${{ github.event.inputs.target }}
